
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
public class Passreset extends javax.swing.JFrame {

    /**
     * Creates new form Passreset
     */
    public Passreset() {this.setUndecorated(true);
        initComponents();
    }
public void genCode(String s){
    l.setText(s);l.setVisible(false);
    ll.setText("Email ID : "+l.getText());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        ll = new javax.swing.JLabel();
        sp = new javax.swing.JCheckBox();
        ll1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setLocationByPlatform(true);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Nehal\\images\\yahoo-icon.png")); // NOI18N
        jLabel1.setText("Y! Messenger");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Password:");

        p1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                p1CaretUpdate(evt);
            }
        });

        ll.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        ll.setText("Email ID :  ");

        sp.setText("Show Password");
        sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spMouseClicked(evt);
            }
        });

        ll1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        ll1.setText("RESET MY PASSWORD");
        ll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ll1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp)
                                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ll1)
                                .addGap(46, 46, 46)))
                        .addComponent(l))
                    .addComponent(ll)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(l))
                .addGap(8, 8, 8)
                .addComponent(ll)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp)
                .addGap(18, 18, 18)
                .addComponent(ll1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void p1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_p1CaretUpdate
if(sp.isSelected()==true){
    p1.setEchoChar((char)0);
}else{
    p1.setEchoChar('!');
}
        // TODO add your handling code here:
    }//GEN-LAST:event_p1CaretUpdate

    private void ll1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ll1MouseClicked
           String password1 = Arrays.toString(p1.getPassword()); String password2 = password1.trim();
           if(password2.isEmpty() || password2.length()<4){
                JOptionPane.showMessageDialog(this,"Please Write With Minimum 4 Characters Password");                
                }else{
           try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/main", "root", "");
                Statement stmt = (Statement) con.createStatement();
                Statement stmt1 = (Statement) con.createStatement();
                String Query ="SELECT PASSWORD('"+password2+"')";
               ResultSet rs=stmt.executeQuery(Query);rs.next();{
               String password = rs.getNString("PASSWORD('"+password2+"')");
               String Query1 = "UPDATE SIGNUP SET PASSWORD = '"+password+"' WHERE EMAIL = '"+l.getText()+"'";
               stmt.executeUpdate(Query1);
               { JOptionPane.showMessageDialog(this,"Sucessfully Password Changed.\b Please Remember Your Security Questions For Password Reset.");
               Home h = new Home();
               dispose();
               h.setVisible(true);
               }  
            }}catch(ClassNotFoundException | SQLException ex){
    JOptionPane.showMessageDialog(this,ex.getMessage());
}}
        // TODO add your handling code here:
    }//GEN-LAST:event_ll1MouseClicked

    private void spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseClicked
if(sp.isSelected()==true){
    p1.setEchoChar((char)0);
}else{
    p1.setEchoChar('!');
}
        // TODO add your handling code here:
    }//GEN-LAST:event_spMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passreset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l;
    private javax.swing.JLabel ll;
    private javax.swing.JLabel ll1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JCheckBox sp;
    // End of variables declaration//GEN-END:variables
}
