
import java.awt.HeadlessException;
import java.io.BufferedInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Read extends javax.swing.JFrame {

    /**
     * Creates new form Read
     */
    public Read() {this.setUndecorated(true);
        initComponents();
        att.setVisible(false);user.setVisible(false);ext.setVisible(false);
    }

    public void genCodef(String f){
        from.setText(f);
    }
    public void genCodes(String f){
        subject.setText(f);
    }
    public void genCodem(String f){
        ta.setText(f);
    }
    public void genCodet(String f){
        time.setText(f);
    }
    public void genCodea(String f){
        if(!f.isEmpty()){
            att.setVisible(true);ext.setText(f);
        } 
    }
    public void genCodeu(String f){
        user.setText(f);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        att = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        send = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        ext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ReadMessages - Y! Messanger");
        setLocationByPlatform(true);
        setUndecorated(true);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel9.setText("From :");

        from.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        from.setText("From ");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel10.setText("Subject :");

        subject.setEditable(false);
        subject.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel11.setText("Message :");

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        ta.setRows(5);
        ta.setRequestFocusEnabled(false);
        ta.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(ta);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel12.setText("Msg Time:");

        time.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        time.setText("Time");
        time.setEnabled(false);

        att.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        att.setText("  Download Attachment");
        att.setToolTipText("Attach File Before Writting Message");
        att.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attMouseClicked(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        delete.setText("    Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        send.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        send.setText("        Back");
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });

        user.setText("jLabel1");

        ext.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(10, 10, 10))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(from)
                                .addGap(176, 176, 176)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(time)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(user))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 85, Short.MAX_VALUE)
                        .addComponent(att, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(520, Short.MAX_VALUE)
                    .addComponent(ext)
                    .addGap(68, 68, 68)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(from)
                    .addComponent(jLabel12)
                    .addComponent(time)
                    .addComponent(user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(att, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(send))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(ext)
                    .addContainerGap(284, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
Profile p = new Profile();
this.dispose();  
// TODO add your handling code here:
    }//GEN-LAST:event_sendMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
JOptionPane.showMessageDialog(this,"Are You Sure ? \n You Want To Delete Selected Message ?");
String dt=(String)time.getText();
String fro=(String)from.getText();
       try{
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/main", "root", "");
                Statement stmt = (Statement) con.createStatement();
                String Query = "DELETE FROM MSG WHERE REC = '"+user.getText()+"' && SEND = '"+fro+"' && DT = '"+dt+"' ";
                stmt.executeUpdate(Query);
                {
               this.dispose();
           }con.close();stmt.close();
                               
     }catch(ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(null, e.getMessage());
     } 
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void attMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attMouseClicked
try  {Connection con;
            Statement stmt;
        Class.forName("java.sql.DriverManager");
        con = (Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/main", "root", "");
        stmt = (Statement) con.createStatement();
        String Query = "SELECT sendfile,extension,rec,send,dt,msg,subject FROM msg WHERE rec = '"+user.getText()+"' and dt = '"+time.getText()+"' and extension is not null";
ResultSet rs = stmt.executeQuery(Query);
stmt.setMaxRows(1000000);int i = 0;
while(rs.next()) { // for each row
   // take the blob
   String ext = rs.getString("extension");
   String send = rs.getString("send");
   Blob blob = rs.getBlob(1); i++;
   BufferedInputStream is = new BufferedInputStream(blob.getBinaryStream()); 
   Date timeStamp = rs.getDate("dt"); String filn = send+timeStamp;System.out.print(filn);
   FileOutputStream fos = new FileOutputStream("("+filn+")"+ext);
   // you can set the size of the buffer
   byte[] buffer = new byte[2048];
   int r = 0;
   while((r = is.read(buffer))!=-1) {
      fos.write(buffer, 0, r);
      }
   fos.flush();
   fos.close();
   is.close();
   blob.free();
JOptionPane.showMessageDialog(this,i +" File Downloded \n Name :"+filn+ext);}
stmt.close();
    } catch (ClassNotFoundException | SQLException | IOException | HeadlessException ex) {
        JOptionPane.showMessageDialog(this,ex);
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_attMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Read.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Read().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel att;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel ext;
    private javax.swing.JLabel from;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel send;
    private javax.swing.JTextField subject;
    private javax.swing.JTextArea ta;
    private javax.swing.JLabel time;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
